### ISSUE TITLE
Deck View Feature - Collapsable Card View

### ISSUE THREAD

**Issue by crookedneighbor** [crookedneighbor/shambleshark#48]
Mockup: 
![hover](https://user-images.githubusercontent.com/2916945/80133187-7685f080-8562-11ea-8df1-d4fd276b3589.gif)

Suggested CSS from @morgunkorn

```css
@media screen and (min-width: 920px) {
  .deck .card-grid-item:nth-child(n+5) {
    margin-top: -25%;
  }
  .deck .card-grid-item:hover {
    z-index: 1;
  }
}
```

Should be simple enough to add additional media queries for other widths to catch screen sizes that have fewer cards per row.

Also could be good to make the level of collapsibility adjustable. Perhaps:

* None
* Compessed (what the mockup/css provided is)
* Super Compressed (only the name visible)

In addition, would be nice to get it configured so that on hover it smoothly reveals the card instead of having it look so jumpy.
